{
 "title": "Django Backend Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count[5m])"
    }
   ]
  },
  {
   "title": "Targets UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}