name: CI

on:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'

      - name: install uv
        uses: astral-sh/setup-uv@v4

      - name: install dependencies
        run: uv sync --locked --all-extras

      - name: tests back
        run: uv run pytest weather/tests/ --junitxml=report.xml

      - name: upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-back
          path: backend/report.xml

      - name: lint
        run: uv run ruff check .

      - name: test with bandit
        run: uv run bandit -r . --exclude ./.venv -f json -o bandit.json || true

      - name: upload bandit report
        uses: actions/upload-artifact@v4
        with:
          name: scan-code-report
          path: backend/bandit.json

      - name: build backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/meteo-app:latest .

      - name: trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/meteo-app:latest
          format: json
          output: backend/trivy-report.json
          exit-code: '0'
          severity: CRITICAL,HIGH

      - name: upload trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: backend/trivy-report.json
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push backend
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/meteo-app:latest
  frontend:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: frontend

      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: install node
          uses: actions/setup-node@v4
          with:
            node-version: '24'

        - name: install dependencies
          run: npm ci

        - name: lint
          run: npm run lint

        - name: build frontend
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/meteo-front:latest .

        - name: trivy
          uses: aquasecurity/trivy-action@0.35.0
          with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/meteo-front:latest
            format: json
            output: frontend/front-report.json
            exit-code: '0'
            severity: CRITICAL,HIGH

        - name: upload trivy report
          uses: actions/upload-artifact@v4
          with:
            name: front-report
            path: frontend/front-report.json

        - name: login dockerhub
          if: github.ref == 'refs/heads/main'
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: push frontend
          if: github.ref == 'refs/heads/main'
          run: docker push ${{ secrets.DOCKER_USERNAME }}/meteo-front:latest

